before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: eobylsbROql0A6gLsLEdqXrS8s/mvU9idvY43sRGYP+ma8snWX933wYFG8xZ7ltr9nLtmr735rZj99zyzrZCueNxR4Q5N87iNNfpwU624Rvszj8wrO8mnC8lasEr5D1jfEeqsJ3mOBFujzPcXG66MFf2a4RLxjZQmVp8/YiRr3TKqCKnToY1x8oaE2S4lF2235yJQqa5c/LcHHSRuIY7WXwKukOmQfX0MXTwRJDB7ZkWFUh+cdu1eGh/VRLiAOGumHXAHzHo5QWJrDMnMzKkLdDohjkaK5Pg9sEBSB3DQVp/zMICrZco5iwDKQed4V1FgQcnTcf+uXO2Ic6UaMZjNES6DAFsVxlO3dyKLpEEbki5FFZ6Kg4ds2f0Zyi1N3GqiNDVXK8R5eBMYjfxoeAieEgiNKdTDcBbCuF/wqhtbUjCHPkwH9O1d78MkOypW1zcgs58d39CQjthW9MSanf29eWUdFCroUa8DIjmqSkZSXGW7kHrZe21mYYwfYPuNLP3jyPq/TPawmi7G38WK2altNbVT3VPF7TPk5ba1s3a1NruX/+BT+ihjWQR/KJ5dlM+BCwkpglRfWmtiPwsUU0oBgWNiTJPbrAGEQ+Eu64LNa/AHMuykp9OkhQ1ZN2Ww7lSa6D+Nm7m8Vx8E6OutY7qpvrinkM0IIMJLNrf/H2m94c= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
